# Generated by Django 4.1.3 on 2022-11-27 13:52

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Count',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(99)], verbose_name='Количество')),
            ],
            options={
                'verbose_name': 'Количество',
                'verbose_name_plural': 'Количества',
                'ordering': ('order__number',),
            },
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Скидка')),
                ('percentage', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(99)], verbose_name='Процент')),
                ('stripes_id', models.CharField(blank=True, max_length=40, verbose_name='идентификатор на сервере')),
            ],
            options={
                'verbose_name': 'Скидка',
                'verbose_name_plural': 'Скидки',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('price_in_usd', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена в долларах')),
                ('price_in_eur', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена в евро')),
                ('price_in_chf', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена во франках')),
                ('currency', models.CharField(choices=[('usd', 'usd'), ('eur', 'eur'), ('chf', 'chf')], max_length=3, verbose_name='Валюта')),
                ('stripes_id', models.CharField(blank=True, max_length=40, verbose_name='идентификатор на сервере')),
                ('price_id', models.CharField(blank=True, max_length=40, verbose_name='идентификатор цены на сервере')),
                ('discount', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='discount_items', to='items.discount', verbose_name='скидки')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Налог')),
                ('description', models.CharField(blank=True, max_length=75, null=True, verbose_name='Описание')),
                ('percentage', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(99)], verbose_name='Процент')),
                ('stripes_id', models.CharField(blank=True, max_length=40, verbose_name='идентификатор на сервере')),
            ],
            options={
                'verbose_name': 'Налог',
                'verbose_name_plural': 'Налоги',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(verbose_name='Номер заказа')),
                ('discount', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='items', to='items.discount', verbose_name='скидки')),
                ('items', models.ManyToManyField(related_name='orders', through='items.Count', to='items.item', verbose_name='товары')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.AddField(
            model_name='item',
            name='taxes',
            field=models.ManyToManyField(related_name='tax_items', to='items.tax', verbose_name='налоги'),
        ),
        migrations.AddField(
            model_name='count',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_counts', to='items.item', verbose_name='Товар'),
        ),
        migrations.AddField(
            model_name='count',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_counts', to='items.order', verbose_name='Заказ'),
        ),
    ]
